# Generated by Django 3.1.3 on 2020-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer name')),
                ('surname', models.CharField(max_length=50, verbose_name='Customer surname')),
                ('email', models.EmailField(max_length=60, verbose_name='Customer contact email')),
                ('number', models.CharField(max_length=20, verbose_name='Customer phone number')),
            ],
            options={
                'verbose_name': 'Customer Contact Detail',
                'verbose_name_plural': 'Customer Contact Details',
            },
        ),
    ]
