# Generated by Django 3.1.3 on 2020-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish_time',
        ),
        migrations.AddField(
            model_name='article',
            name='post_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
