# Generated by Django 3.1.3 on 2020-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201102_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
