# Generated by Django 3.1.3 on 2020-11-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
